name: Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate coverage report
        run: mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      steps:
        - uses: actions/checkout@master
        - uses: codecov/codecov-action@v3
          with:
            files: ./report-aggregator/target/site/jacoco-aggregate/jacoco.xml
            verbose: true # optional (default = false)