name: Coverage

on:
  workflow_call:
    secrets:
      repo_token:
        required: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate coverage report
        run: mvn clean install coveralls:report -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DrepoToken=${{ secrets.repo_token }}
